#!/usr/bin/env python3
"""Generate the Android colour resources from the desktop app's palette.

Hand-copying the hex values would mean the phone drifts away from the desktop
the first time a colour changes and nobody remembers there are two copies.
This reads the one definition in src/lagscope/ui/theme.py and writes the
Android resource file, so "the same as the PC" stays true by construction.

Run it after changing THEMES, and commit the result.
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))
from lagscope.ui.theme import THEMES  # noqa: E402

HERE = pathlib.Path(__file__).resolve().parent
palette = THEMES["dark"]

rows = [
    ("background", palette.background),
    ("foreground", palette.foreground),
    ("muted", palette.muted),
    ("border", palette.border),
    ("accent", palette.accent),
    ("good", palette.good),
    ("warn", palette.warn),
    ("bad", palette.bad),
    # One value the desktop does not name: the raised surface a card sits on.
    # Derived rather than invented, so it moves with the background.
    ("surface", "#" + "".join(
        f"{min(255, int(palette.background[1:][i:i + 2], 16) + 5):02x}"
        for i in (0, 2, 4))),
]

body = "\n".join(f'    <color name="{name}">{value}</color>' for name, value in rows)
out = HERE / "res" / "values" / "colors.xml"
out.write_text(
    '<?xml version="1.0" encoding="utf-8"?>\n'
    "<!-- Generated by sync_theme.py from src/lagscope/ui/theme.py - do not edit. -->\n"
    f"<resources>\n{body}\n</resources>\n", encoding="utf-8")
print(f"wrote {out.relative_to(HERE.parent)}")
for name, value in rows:
    print(f"  {name:<11} {value}")
